#!/bin/bash

#REPLACE THESE ITEMS WHEN CREATING A NEW PROJECT FROM THIS FILE: 'BET_SOCIAL_', 'betSocial'

BET_SOCIAL_PYTHON_VERSION="3"
BET_SOCIAL_REPO_NAME="bet-social"
BET_SOCIAL_GIT_REPO="git@github.com:ITbtn/$BET_SOCIAL_REPO_NAME.git"
BET_SOCIAL_PROJECT_NAME="bet-social"
BET_SOCIAL_CELERY_PROJECT_NAME="BetInformedSPG"
BET_SOCIAL_PROJECT_NAME_UNDERSCORE="bet_social"
BET_SOCIAL_PROJECT_NAME_CAMEL_CASE="betSocial"
BET_SOCIAL_LOCAL_PORT="8004"
BET_SOCIAL_DJANGO_APP_NAMES="activity_configs competitions core image_generators matches messages_library messages_library social_apps stadiums teams"
BET_SOCIAL_POSTGRES_USER="postgres"
BET_SOCIAL_CELERY_FLOWER_HOST="127.0.0.1"
BET_SOCIAL_CELERY_FLOWER_PORT="5556"
BET_SOCIAL_VIRTUAL_ENVIRONMENT_NAME="${BET_SOCIAL_PROJECT_NAME_CAMEL_CASE}Env"

BET_SOCIAL_DJANGO_OPERATIONS="makemigrations migrate"
BET_SOCIAL_INIT_REQUIREMENTS_FILE_NAME='requirement_dev.pip'
BET_SOCIAL_PROJECT_ROOT_FOLDER="$SYSTEM_ROOT_GIT_REPO_FOLDER/$BET_SOCIAL_REPO_NAME/BetInformedSPG"
BET_SOCIAL_INIT_DB_FILE_NAME="${BET_SOCIAL_PROJECT_NAME}-reset-db.sql"
BET_SOCIAL_POSTGRES_USER_PASSWORD_RESET_FILE_NAME="${BET_SOCIAL_PROJECT_NAME}-postgres-password-reset.sql"
BET_SOCIAL_INIT_DATA_LOAD_PYTHON_FILE_NAME="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_init_data_load.py"
BET_SOCIAL_VIRTUAL_ENVIRONMENT_FOLDER="$SYSTEM_ROOT_VIRTUAL_PYTHON_ENVIRONMENT_FOLDER/$BET_SOCIAL_VIRTUAL_ENVIRONMENT_NAME"
BET_SOCIAL_INIT_POSTGRES_DB_FILE_PATH="$BASH_TEMP_FOLDER/$BET_SOCIAL_INIT_DB_FILE_NAME"
BET_SOCIAL_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH="$BASH_TEMP_FOLDER/$BET_SOCIAL_POSTGRES_USER_PASSWORD_RESET_FILE_NAME"

BET_SOCIAL_INIT_DATA_LOAD_PYTHON_FILE_PATH="$BASH_TEMP_FOLDER/$BET_SOCIAL_INIT_DATA_LOAD_PYTHON_FILE_NAME"

if [ -f $BASH_TEMP_FOLDER/django-project-core.sh ]; then
    . $BASH_TEMP_FOLDER/django-project-core.sh
fi;

alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bc="djangoBranchChange $BET_SOCIAL_PROJECT_NAME_UNDERSCORE "
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bc_full_reset="djangoBranchChangeWithFullReset $BET_SOCIAL_PROJECT_NAME_UNDERSCORE "
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bc_full_reset_and_run="djangoBranchChangeWithFullResetAndRun $BET_SOCIAL_PROJECT_NAME_UNDERSCORE "
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bcd="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bc develop"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bcd_full_reset="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bc_full_reset develop"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bcd_full_reset_and_run="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bc_full_reset_and_run develop"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bcd_run="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_bcd && ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_run"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_db_shell="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve && ./manage.py shell"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_dir="goToDir \"$BET_SOCIAL_PROJECT_ROOT_FOLDER\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_frr="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_full_reset && ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_run"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_full_reset="djangoFullReset $BET_SOCIAL_PROJECT_NAME_UNDERSCORE"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_gf="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_dir && git_f"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_git_setup="djangoGitSetup $BET_SOCIAL_GIT_REPO"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_last_10_commit_hash="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_dir && git log -10 --pretty=format:\"%h\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_loc="cloc \"$BET_SOCIAL_PROJECT_ROOT_FOLDER\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_reinitiate="djangoReinitiate \"$BET_SOCIAL_PROJECT_ROOT_FOLDER\" \"$BET_SOCIAL_DJANGO_APP_NAMES\" $BET_SOCIAL_INIT_DATA_LOAD_PYTHON_FILE_PATH \"$BET_SOCIAL_DJANGO_OPERATIONS\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_reinitiate_clean="djangoReinitiateClean \"$BET_SOCIAL_PROJECT_ROOT_FOLDER\" \"$BET_SOCIAL_DJANGO_OPERATIONS\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_postgres_shell="psql -U $BET_SOCIAL_POSTGRES_USER"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_postgres_user_password_reset="postgresPasswordReset \"$BET_SOCIAL_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_process_id="lsof -i:${BET_SOCIAL_LOCAL_PORT} | awk '{print $2}'"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_psql_reset="djangoPsqlReset $BET_SOCIAL_POSTGRES_USER \"$BET_SOCIAL_INIT_POSTGRES_DB_FILE_PATH\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_reset="djangoReset $BET_SOCIAL_PROJECT_NAME_UNDERSCORE"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_rr="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_reset && ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_run"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_rt="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_reset && ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_test"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_run="djangoRun $BET_SOCIAL_PROJECT_NAME_UNDERSCORE $BET_SOCIAL_PROJECT_NAME_UNDERSCORE $BET_SOCIAL_LOCAL_PORT"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_run_production="djangoProductionRun $BET_SOCIAL_PROJECT_NAME_UNDERSCORE $BET_SOCIAL_PROJECT_NAME $BET_SOCIAL_LOCAL_PORT"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_run_generic_deployment="djangoDeploymentOperations $BET_SOCIAL_PROJECT_NAME_UNDERSCORE"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_start_celery="startCeleryWorkers $BET_SOCIAL_CELERY_PROJECT_NAME $BET_SOCIAL_CELERY_FLOWER_HOST $BET_SOCIAL_CELERY_FLOWER_PORT"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_stop_processes="djangoStopProcesses $BET_SOCIAL_LOCAL_PORT $BET_SOCIAL_CELERY_PROJECT_NAME"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_test="djangoTest $BET_SOCIAL_PROJECT_NAME_UNDERSCORE"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve="djangoUseVe \"$BET_SOCIAL_VIRTUAL_ENVIRONMENT_FOLDER\" $BET_SOCIAL_PROJECT_NAME_UNDERSCORE"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve_check="checkVirtualPythonEnvironmentFolder \"$BET_SOCIAL_VIRTUAL_ENVIRONMENT_FOLDER\" \"$SYSTEM_ROOT_VIRTUAL_PYTHON_ENVIRONMENT_FOLDER\" $BET_SOCIAL_VIRTUAL_ENVIRONMENT_NAME"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve_clear="djangoVeClear \"$SYSTEM_ROOT_VIRTUAL_PYTHON_ENVIRONMENT_FOLDER\" $BET_SOCIAL_VIRTUAL_ENVIRONMENT_NAME"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve_init="pythonVeVersionDecider \"$BET_SOCIAL_VIRTUAL_ENVIRONMENT_FOLDER\" \"$SYSTEM_ROOT_VIRTUAL_PYTHON_ENVIRONMENT_FOLDER\" $BET_SOCIAL_VIRTUAL_ENVIRONMENT_NAME $BET_SOCIAL_PROJECT_NAME \"$BET_SOCIAL_PYTHON_VERSION\""
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve_installs="djangoDefaultSetup \"$BET_SOCIAL_PROJECT_ROOT_FOLDER\" $BET_SOCIAL_INIT_REQUIREMENTS_FILE_NAME $BET_SOCIAL_PROJECT_NAME_UNDERSCORE"
alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_installs="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve_init && cd \"$SYSTEM_ROOT_GIT_REPO_FOLDER\" && git clone ${BET_SOCIAL_GIT_REPO} && ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve_installs && ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_dir"

betSocialManagementCommands() {
  printf "yes\n" | ./manage.py fetch_and_create_stadiums
  printf "yes\n" | ./manage.py fetch_and_create_competitions
  printf "yes\n" | ./manage.py fetch_and_create_teams
  printf "yes\n" | ./manage.py fetch_and_create_matches
}

alias ${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_data_load="${BET_SOCIAL_PROJECT_NAME_UNDERSCORE}_ve && betSocialManagementCommands"
