#!/bin/bash

if [ -f $BASH_TEMP_FOLDER/epad-project-core.sh ]; then
    . $BASH_TEMP_FOLDER/epad-project-core.sh
fi;

#global variable overrides
EPAD_INIT_POSTGRES_DB_FILE_PATH="$BASH_TEMP_FOLDER/$EPAD_INIT_DB_FILE_NAME"
EPAD_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH="$BASH_TEMP_FOLDER/$EPAD_POSTGRES_USER_PASSWORD_RESET_FILE_NAME"
EPAD_INIT_DATA_LOAD_PYTHON_FILE_PATH="$BASH_TEMP_FOLDER/$EPAD_INIT_DATA_LOAD_PYTHON_FILE_NAME"
