#!/bin/bash

if [ -f $BASH_TEMP_FOLDER/fleks-project-core.sh ]; then
    . $BASH_TEMP_FOLDER/fleks-project-core.sh
fi;

#global variable overrides
FLEKS_INIT_POSTGRES_DB_FILE_PATH="$BASH_TEMP_FOLDER/$FLEKS_INIT_DB_FILE_NAME"
FLEKS_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH="$BASH_TEMP_FOLDER/$FLEKS_POSTGRES_USER_PASSWORD_RESET_FILE_NAME"
