#!/bin/bash

if [ -f $BASH_HELPER_GIT_FOLDER/fleks-project-core.sh ]; then
    . $BASH_HELPER_GIT_FOLDER/fleks-project-core.sh
fi;

#global variable overrides
FLEKS_INIT_POSTGRES_DB_FILE_PATH="$BASH_TEMP_FOLDER/$FLEKS_INIT_DB_FILE_NAME"
FLEKS_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH="$BASH_TEMP_FOLDER/$FLEKS_POSTGRES_USER_PASSWORD_RESET_FILE_NAME"

alias ${FLEKS_PROJECT_NAME_UNDERSCORE}_postgres_user_password_reset="postgresPasswordReset $FLEKS_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH"
alias ${FLEKS_PROJECT_NAME_UNDERSCORE}_psql_reset="djangoPsqlReset $FLEKS_POSTGRES_USER $FLEKS_INIT_POSTGRES_DB_FILE_PATH"
