#!/bin/bash

if [ -f $BASH_HELPER_GIT_FOLDER/tin-infra-project-core.sh ]; then
    . $BASH_HELPER_GIT_FOLDER/tin-infra-project-core.sh
fi;

TIN_INFRA_INIT_POSTGRES_DB_FILE_PATH="$BASH_TEMP_FOLDER/$TIN_INFRA_INIT_DB_FILE_NAME"
TIN_INFRA_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH="$BASH_TEMP_FOLDER/$TIN_INFRA_POSTGRES_USER_PASSWORD_RESET_FILE_NAME"
TIN_INFRA_INIT_DATA_LOAD_PYTHON_FILE_PATH="$BASH_TEMP_FOLDER/$TIN_INFRA_INIT_DATA_LOAD_PYTHON_FILE_NAME"

alias ${TIN_INFRA_PROJECT_NAME_UNDERSCORE}_init_data_load="${TIN_INFRA_PROJECT_NAME_UNDERSCORE}_ve && ./manage.py shell < $TIN_INFRA_INIT_DATA_LOAD_PYTHON_FILE_PATH"
alias ${TIN_INFRA_PROJECT_NAME_UNDERSCORE}_postgres_user_password_reset="postgresPasswordReset $TIN_INFRA_INIT_POSTGRES_DB_USER_PASSWORD_FILE_PATH"
alias ${TIN_INFRA_PROJECT_NAME_UNDERSCORE}_psql_reset="djangoPsqlReset $TIN_INFRA_POSTGRES_USER $TIN_INFRA_INIT_POSTGRES_DB_FILE_PATH"
alias ${TIN_INFRA_PROJECT_NAME_UNDERSCORE}_reinitiate="djangoReinitiate \"$TIN_INFRA_PROJECT_ROOT_FOLDER\" \"$TIN_INFRA_DJANGO_APP_NAMES\" $TIN_INFRA_INIT_DATA_LOAD_PYTHON_FILE_PATH \"$TIN_INFRA_DJANGO_OPERATIONS\""
alias ${TIN_INFRA_PROJECT_NAME_UNDERSCORE}_reset_clean="djangoResetWithoutMigrationClean $TIN_INFRA_PROJECT_NAME_UNDERSCORE $TIN_INFRA_INIT_DATA_LOAD_PYTHON_FILE_PATH"
alias ${TIN_INFRA_PROJECT_NAME_UNDERSCORE}_start_celery="startCeleryWorkers $TIN_INFRA_CELERY_PROJECT_NAME $TIN_INFRA_CELERY_FLOWER_HOST $TIN_INFRA_CELERY_FLOWER_PORT"
